import Link from "next/link";
export default function TermsPage() {
  const sections = [
    { title: "Acceptance of Terms", content: "By accessing or using MockMate, you agree to be bound by these Terms of Service. If you do not agree, please do not use our service." },
    { title: "Use of Service", content: "MockMate provides AI-powered interview simulation for candidates and hiring tools for companies. You may use MockMate only for lawful purposes and in accordance with these terms. You must be at least 16 years old to use this service." },
    { title: "Candidate Accounts", content: "As a candidate, you may create an account to access interview practice features. You are responsible for maintaining the confidentiality of your account credentials. Interview results may be shared with companies whose interview links you use." },
    { title: "Company Accounts", content: "As a company, you may create an account to access hiring portal features. You are responsible for ensuring candidates are informed that interviews are AI-conducted and proctored. You may not use MockMate to discriminate unlawfully against candidates." },
    { title: "Proctoring and Data Collection", content: "MockMate uses camera access for face detection during interviews. By starting an interview, you consent to this proctoring. Video is processed locally and not stored. Proctoring results (face detection flags, tab switches) are stored and shared with the hiring company." },
    { title: "AI-Generated Content", content: "Interview feedback is generated by AI and is for informational purposes only. MockMate does not guarantee the accuracy of AI-generated feedback. Hiring decisions should not be based solely on MockMate scores." },
    { title: "Intellectual Property", content: "MockMate and its content are owned by MockMate. You may not copy, modify, or distribute our software, design, or content without permission." },
    { title: "Limitation of Liability", content: "MockMate is provided 'as is'. We are not liable for any damages arising from your use of the service, including hiring decisions made based on our platform." },
    { title: "Changes to Terms", content: "We may update these terms at any time. Continued use of MockMate after changes constitutes acceptance of the new terms." },
    { title: "Contact", content: "For questions about these terms, contact us at contact@mockmate.pk." },
  ];
  return (
    <div style={{ background: "#0A0C10", color: "#e2e2e8", minHeight: "100vh", fontFamily: "Inter, sans-serif" }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=Geist:wght@600;700&display=swap');`}</style>
      <header style={{ padding: "0 24px", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
        <div style={{ display: "flex", alignItems: "center", maxWidth: 1280, margin: "0 auto", height: 64 }}>
          <Link href="/" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
            <div style={{ width: 32, height: 32, borderRadius: "50%", background: "linear-gradient(135deg, #00dbe9, #7000ff)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 700, color: "#fff" }}>M</div>
            <span style={{ fontSize: 20, fontWeight: 700, color: "#dbfcff", fontFamily: "Geist, sans-serif" }}>MockMate</span>
          </Link>
        </div>
      </header>
      <main style={{ maxWidth: 800, margin: "0 auto", padding: "80px 24px" }}>
        <span style={{ fontSize: 11, fontFamily: "JetBrains Mono, monospace", color: "#00dbe9", letterSpacing: "0.1em", textTransform: "uppercase" }}>Legal</span>
        <h1 style={{ fontSize: 42, fontWeight: 700, fontFamily: "Geist, sans-serif", color: "#fff", margin: "16px 0 8px" }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: "#849495", marginBottom: 48, fontFamily: "JetBrains Mono, monospace" }}>Last updated: June 2026</p>
        {sections.map(({ title, content }) => (
          <div key={title} style={{ marginBottom: 40, paddingBottom: 40, borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
            <h2 style={{ fontSize: 20, fontWeight: 700, fontFamily: "Geist, sans-serif", color: "#dbfcff", marginBottom: 12 }}>{title}</h2>
            <p style={{ fontSize: 15, color: "#849495", lineHeight: 1.8 }}>{content}</p>
          </div>
        ))}
      </main>
    </div>
  );
}
